export var DOCUMENT_STATUS;
(function (DOCUMENT_STATUS) {
    DOCUMENT_STATUS["PROCESSING"] = "PROCESSING";
    DOCUMENT_STATUS["UPLOADED"] = "UPLOADED";
    DOCUMENT_STATUS["DELETING"] = "DELETING";
    DOCUMENT_STATUS["DELETED"] = "DELETED";
})(DOCUMENT_STATUS || (DOCUMENT_STATUS = {}));
